# Generated by Django 2.0 on 2018-02-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpro', '0003_auto_20180220_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('actual', models.BooleanField(default=True)),
            ],
        ),
    ]
