# Generated by Django 2.0 on 2018-02-25 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpro', '0004_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
