# Generated by Django 2.0 on 2018-02-25 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpro', '0005_auto_20180225_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_vacancy', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpro.Vacancy')),
            ],
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
