# Generated by Django 2.0 on 2018-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpro', '0009_vacancy_org_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
